services:
  - type: web
    name: saigonride
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: saigonride-db
          property: connectionString

databases:
  - name: saigonride-db
    databaseName: saigonride
    plan: free
