services:
  - type: web
    name: saigonride
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DB_HOST
        fromDatabase:
          name: saigonride-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: saigonride-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: saigonride-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: saigonride-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: saigonride-db
          property: password
      - key: Email__Username
        sync: false
      - key: Email__Password
        sync: false
      - key: Email__FromAddress
        sync: false

databases:
  - name: saigonride-db
    databaseName: saigonride
    plan: free
